#!/usr/bin/env bash
# Copyright 2025 the V-Gate authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Bring up the split topology on a local kind cluster and prove it works.
#
# "The manifests pass validation" and "the manifests deploy a working system"
# are different claims, and only the second one is worth anything. This script
# makes the second one reproducible: it deploys, serves a real request through
# the gateway to a worker, kills a worker, shows the gateway keeping service up
# on the survivor, and shows the worker rejoining rotation when it comes back.
#
# Everything it prints goes to an evidence file so the result can be checked in
# rather than described.
#
# Requires: docker, kind, kubectl, kustomize, python3
# Usage:    ./k8s/kind-verify.sh [--keep]
#           --keep   leave the cluster running afterwards

set -euo pipefail

CLUSTER=vgate
NS=vgate
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE="${REPO_ROOT}/docs/reports/K8S_SPLIT_VERIFICATION.md"
RAW="$(mktemp)"
PORT=18000
KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

PF_PID=""
PROBE_PID=""
cleanup() {
    [[ -n "$PF_PID" ]] && kill "$PF_PID" 2>/dev/null || true
    [[ -n "$PROBE_PID" ]] && kill "$PROBE_PID" 2>/dev/null || true
    if [[ $KEEP -eq 0 ]]; then
        kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
    fi
    # Restore the real stdout before writing the report, so this output does
    # not loop back into the log being read.
    exec 1>&3 2>&3
    sleep 1  # let tee flush
    {
        echo "# Kubernetes Split Topology Verification"
        echo
        echo "Generated by \`k8s/kind-verify.sh\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
        echo "Regenerate with \`./k8s/kind-verify.sh\`; do not edit by hand."
        echo
        if [[ "${FAILURES:-0}" -eq 0 ]]; then
            echo "**Result: all assertions passed.**"
        else
            echo "**Result: ${FAILURES} assertion(s) FAILED.** This report documents a run"
            echo "that did not verify. Read the \`[FAIL]\` lines below."
        fi
        echo
        echo "The \`[PASS]\`/\`[FAIL]\` lines are the actual checks; the surrounding"
        echo "output is context for reading them. The script exits non-zero when any"
        echo "assertion fails, so a wrong topology cannot produce a passing run."
        echo
        echo "Deploys the gateway/worker split on a local kind cluster, serves a"
        echo "request end to end, removes a worker while traffic is flowing, and"
        echo "brings it back."
        echo
        echo "## What to read in the log below"
        echo
        echo "- **Step 6** — the \`NODE\` column. The two workers must land on"
        echo "  different nodes, or the per-pod routing below never crosses a"
        echo "  network boundary and proves less than it appears to. The two"
        echo "  bound PVCs are the same point for storage: a single"
        echo "  \`ReadWriteOnce\` claim could not serve pods on two nodes."
        echo "- **Step 7** — the two DNS answers must be *different* addresses."
        echo "  One shared address would leave the gateway unable to tell"
        echo "  workers apart, and is what a load-balanced Service IP gives."
        echo "- **Step 10** — request counts should be split across both"
        echo "  workers. This is round-robin; it is not load-aware."
        echo "- **Step 11** — the status-code histogram is the real result."
        echo "  Requests keep flowing while a worker is removed, so this counts"
        echo "  what the removal cost. All \`200\` is common but not guaranteed:"
        echo "  read the outcome metrics printed underneath before concluding"
        echo "  anything from a non-200. A \`connect_error\` was never delivered"
        echo "  and gets retried on another worker; a \`request_error\` was"
        echo "  already in flight when the pod died and is deliberately not"
        echo "  retried, because the worker may already be generating and one"
        echo "  client request must not cost two generations. The second class"
        echo "  reaching the client as a 500 is the policy working, not a bug."
        echo "  Removing that window needs draining — see ROADMAP.md."
        echo "- **Step 12** — the point of DNS discovery. \`kubectl scale\` is"
        echo "  run against the StatefulSet and the gateway is expected to pick"
        echo "  the change up on its own. With the static endpoint list this"
        echo "  replaced, a new pod received no traffic and a removed one was"
        echo "  probed forever, and the only fix was editing the gateway's"
        echo "  manifest. Endpoints must also read as \`vgate-worker-<n>.\`"
        echo "  rather than as addresses: a restarted pod returns on a new IP,"
        echo "  and every \`vgate_worker_*\` metric is labelled by endpoint, so"
        echo "  address identity would add a time series per restart. The run"
        echo "  also scales to zero and back, which is the boundary an earlier"
        echo "  version skipped by going 1 -> 3 -> 2: an empty resolve is"
        echo "  ambiguous, and the first guard against DNS blips ignored empty"
        echo "  answers unconditionally, keeping the last worker in the"
        echo "  registry forever."
        echo "- **Step 13** — \`state_changes_total\` normally shows one extra"
        echo "  removed/recovered pair per worker beyond the scripted one. That"
        echo "  is the cold start: the gateway passes its readiness probe and"
        echo "  begins probing before any worker is up. See the readiness gap"
        echo "  noted in ROADMAP.md — a gateway with zero healthy workers is"
        echo "  still Ready as far as Kubernetes is concerned."
        echo
        echo '```'
        cat "$RAW"
        echo '```'
    } > "$EVIDENCE"
    rm -f "$RAW"
    echo "Evidence written to ${EVIDENCE}"
}
trap cleanup EXIT

mkdir -p "$(dirname "$EVIDENCE")"
exec 3>&1                        # keep a handle on the real stdout
exec > >(tee "$RAW") 2>&1

step() { printf '\n\n========== %s ==========\n' "$1"; }

# Assertions, not observations. Printing a pod list and letting a human decide
# whether it looks right means a wrong topology still produces a report that
# says "Done" and exits 0 — which is the same trap as a test suite that only
# ever runs the passing path. Every claim this script makes in its summary is
# checked here, and the script exits non-zero if any of them does not hold.
FAILURES=0
claim() {  # claim <0|1 ok> <description>
    if [[ "$1" -eq 0 ]]; then
        printf '  [PASS] %s\n' "$2"
    else
        printf '  [FAIL] %s\n' "$2"
        FAILURES=$((FAILURES + 1))
    fi
}
# Sum a Prometheus metric family from the gateway, 0 when absent.
#
# The `|| true` is load-bearing. With `set -o pipefail`, grep finding nothing
# fails the whole pipeline, the command substitution fails, and `set -e` kills
# the script — which meant this aborted precisely when no failures had been
# recorded, i.e. on the happy path. Found by a negative test, not by the many
# runs where the metric happened to exist.
metric_sum() {
    curl -s "http://localhost:${PORT}/metrics" \
        | { grep -E "$1" || true; } \
        | awk '{s += $NF} END {print s + 0}'
}

for tool in docker kind kubectl kustomize python3; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool"; exit 1; }
done

step "0. Versions"
kind version
kubectl version --client
kustomize version

step "1. Build the CPU image"
# Tag read from the manifests rather than hardcoded, so a version bump there
# cannot leave this script building an image nothing references.
IMAGE="$(kustomize build "${REPO_ROOT}/k8s/overlays/cpu" | python3 -c '
import sys, yaml
for d in yaml.safe_load_all(sys.stdin):
    if d and d.get("kind") == "Deployment" and d["metadata"]["name"] == "vgate-gateway":
        print(d["spec"]["template"]["spec"]["containers"][0]["image"]); break
')"
echo "image from manifests: ${IMAGE}"
docker build --target vgate-cpu -t "$IMAGE" "$REPO_ROOT"

step "2. Create the cluster"
kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
kind create cluster --name "$CLUSTER" --config "${REPO_ROOT}/k8s/kind-cluster.yaml"

step "3. Side-load the image"
# kind nodes cannot pull from the host daemon, and the manifests set
# imagePullPolicy: IfNotPresent so this copy is the one that gets used.
kind load docker-image "$IMAGE" --name "$CLUSTER"

step "4. Apply the CPU overlay"
# `kustomize build | kubectl apply` rather than `kubectl apply -k`, so the
# kustomize version is the one this repo pins in CI, not whatever kubectl
# happens to embed.
kustomize build "${REPO_ROOT}/k8s/overlays/cpu" | kubectl apply -f -

step "5. Wait for both roles to become ready"
kubectl -n "$NS" rollout status deployment/vgate-gateway --timeout=180s
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s

step "6. What actually got scheduled"
kubectl -n "$NS" get pods -o wide
echo
kubectl -n "$NS" get svc,statefulset,deployment,pvc
echo
worker_nodes="$(kubectl -n "$NS" get pods \
    -l app.kubernetes.io/component=worker \
    -o jsonpath='{range .items[*]}{.spec.nodeName}{"\n"}{end}' | sort -u | wc -l)"
claim "$([[ "$worker_nodes" -eq 2 ]] && echo 0 || echo 1)" \
    "the two workers are on different nodes (distinct nodes: ${worker_nodes})"

step "7. Worker DNS resolves per pod"
# The claim under test: each worker has its own address. One shared address
# would mean the gateway cannot tell workers apart. A failure here used to be
# swallowed by `|| echo`, which turned the single most load-bearing check in
# this script into a comment.
dns_out="$(kubectl -n "$NS" run dnstest --rm -i --restart=Never --quiet --image=busybox:1.36 -- \
    sh -c 'sleep 1; for i in 0 1; do echo "--- vgate-worker-$i ---"; nslookup vgate-worker-$i.vgate-worker.vgate.svc.cluster.local; done' \
    2>/dev/null || true)"
echo "$dns_out"
echo
# Every IPv4 in the answer except the cluster DNS server's own address.
dns_server="$(kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}')"
# Guarded because the interesting failure is DNS returning nothing at all: with
# pipefail an unmatched grep would abort the script instead of letting the
# assertion below report it.
resolved="$(echo "$dns_out" | { grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' || true; } \
    | { grep -vx "$dns_server" || true; } | sort -u)"
resolved_count="$(echo "$resolved" | { grep -c . || true; })"
echo "distinct worker addresses resolved: ${resolved_count}"
echo "$resolved" | sed 's/^/  /'
claim "$([[ "$resolved_count" -eq 2 ]] && echo 0 || echo 1)" \
    "each worker resolves to its own address (distinct: ${resolved_count}, want 2)"

step "8. Port-forward the gateway"
kubectl -n "$NS" port-forward svc/vgate "${PORT}:8000" >/dev/null 2>&1 &
PF_PID=$!
for _ in $(seq 1 30); do
    curl -sf "http://localhost:${PORT}/health" >/dev/null && break
    sleep 1
done
curl -s "http://localhost:${PORT}/health"; echo

API_KEY="$(kubectl -n "$NS" get secret vgate-secrets -o jsonpath='{.data.api-key}' | base64 -d)"

ask() {
    curl -s -X POST "http://localhost:${PORT}/v1/chat/completions" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"$1\"}],\"max_tokens\":16}"
}
workers() {
    curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
        | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'
}

step "9. A real request, gateway -> worker"
# Unique prompt each run: a cached answer would prove nothing about routing.
first_answer="$(ask "kind verification $(date +%s)")"
echo "$first_answer"
echo
echo "--- worker registry ---"
workers
echo
echo "$first_answer" | grep -q '"choices"' && rc=0 || rc=1
claim "$rc" "the gateway served a completion end to end"

step "10. Spread requests and confirm both workers were used"
RUN_ID="$(date +%s)"
for i in $(seq 1 8); do ask "spread probe ${RUN_ID} $i" >/dev/null; done
echo "--- per-worker request counts from the gateway's metrics ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total' || true
echo
workers_used="$(curl -s "http://localhost:${PORT}/metrics" \
    | { grep '^vgate_worker_requests_total{outcome="success"' || true; } | wc -l)"
claim "$([[ "$workers_used" -eq 2 ]] && echo 0 || echo 1)" \
    "requests reached both workers (workers with successes: ${workers_used})"

step "11. Remove a worker while traffic is flowing"
# The interesting window is not after the gateway has noticed the worker is
# gone — it is the ~10s before it notices (health_check_interval 5s x
# failure_threshold 2), when requests are still being routed to a pod that no
# longer exists. Serving traffic across the removal is what shows what that
# costs; asking once afterwards would only show the steady state.
#
# Scaling down rather than deleting the pod: a deleted pod is recreated
# immediately and a dry-run worker restarts in a few seconds, so the restart
# races the detection and the removed state can be missed entirely. Scaling to
# 1 removes the highest ordinal and keeps it gone.
PROBE_LOG="$(mktemp)"
STOP_FLAG="$(mktemp -u)"
(
    n=0
    while [[ ! -e "$STOP_FLAG" ]]; do
        n=$((n + 1))
        # Unique prompt per probe, so a cache hit can never stand in for a
        # successful round trip to a worker.
        code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
            -X POST "http://localhost:${PORT}/v1/chat/completions" \
            -H "Authorization: Bearer ${API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"failover probe ${RUN_ID} ${n}\"}],\"max_tokens\":8}" \
            || echo "000")
        echo "$code" >> "$PROBE_LOG"
        sleep 0.25
    done
) &
PROBE_PID=$!

kubectl -n "$NS" scale statefulset/vgate-worker --replicas=1
kubectl -n "$NS" wait --for=delete pod/vgate-worker-1 --timeout=60s || true
echo "--- traffic continues while the health checker catches up ---"
sleep 20

touch "$STOP_FLAG"
wait "$PROBE_PID" 2>/dev/null || true
echo "--- HTTP status codes seen across the removal ---"
sort "$PROBE_LOG" | uniq -c
echo "    (000 = no response; 503 = every worker down; 200 = served)"

probe_total="$(wc -l < "$PROBE_LOG")"
probe_200="$(grep -cx 200 "$PROBE_LOG" || true)"
probe_000="$(grep -cx 000 "$PROBE_LOG" || true)"
probe_503="$(grep -cx 503 "$PROBE_LOG" || true)"
probe_other=$((probe_total - probe_200 - probe_000 - probe_503))
rm -f "$PROBE_LOG" "$STOP_FLAG"

echo
# Which failure class the gateway saw matters more than the count. The retry
# policy is keyed on what the worker could already have started:
#   connect_error  nothing was delivered, so another worker takes it
#   request_error  the worker may already be generating, so it is NOT retried
#                  — one client request must not cost two generations
# A non-200 above should correspond to a request_error here, not a lost retry.
echo "--- outcomes recorded per worker ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total' || true
echo "--- retries onto another worker ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_retries_total' || true

echo
echo "--- worker registry after detection ---"
workers_json="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}")"
echo "$workers_json" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'

echo
request_errors="$(metric_sum '^vgate_worker_requests_total\{outcome="request_error"')"
claim "$([[ "$probe_000" -eq 0 ]] && echo 0 || echo 1)" \
    "no request went unanswered (000 responses: ${probe_000})"
claim "$([[ "$probe_503" -eq 0 ]] && echo 0 || echo 1)" \
    "the pool never reported itself empty while one worker was up (503s: ${probe_503})"
# A non-200 is acceptable only when it is the documented un-retryable class: a
# request already in flight when the pod died. Anything beyond that count means
# requests were lost somewhere the retry policy was supposed to cover.
claim "$([[ "$probe_other" -le "${request_errors%.*}" ]] && echo 0 || echo 1)" \
    "every non-200 is an un-retryable mid-flight failure (other: ${probe_other}, request_error: ${request_errors})"
# What "the worker left rotation" means changed when discovery landed, and the
# assertion had to change with it rather than be relaxed until it passed.
#
# With a static endpoint list, a scaled-away worker stayed a known member and
# was marked unhealthy, so the check was `unhealthy == 1`. It is now dropped
# from DNS, so the registry stops tracking it entirely — a strictly better
# outcome, since nothing keeps probing a pod that is never coming back, and
# nothing keeps a `vgate_worker_healthy` series alive for it.
#
# Health-based removal still exists for the case discovery cannot see: a pod
# present in DNS whose server is not answering. That path is covered by
# tests/test_worker_registry.py and by the cold-start transitions visible in
# step 13's metrics, and is not forced into this script, where producing a
# wedged-but-present pod reliably is more machinery than the coverage is worth.
known="$(echo "$workers_json" | python3 -c '
import json, sys
print(len(json.load(sys.stdin).get("workers") or []))')"
serving="$(echo "$workers_json" | python3 -c '
import json, sys
w = json.load(sys.stdin).get("workers") or []
print(sum(1 for x in w if x["healthy"]))')"
claim "$([[ "$known" -eq 1 ]] && echo 0 || echo 1)" \
    "the departed worker is forgotten, not probed forever (known workers: ${known}, want 1)"
claim "$([[ "$serving" -eq 1 ]] && echo 0 || echo 1)" \
    "the survivor is still serving (healthy workers: ${serving}, want 1)"

step "12. kubectl scale reaches the gateway"
# The claim discovery exists to make true. With a static endpoint list, scaling
# the StatefulSet changed nothing on the gateway: a new pod received no traffic
# because the gateway had never been told about it, and the only way to inform
# it was editing and reapplying its manifest.
echo "--- registry before scaling out ---"
before_count="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
    | python3 -c 'import json,sys; print(len(json.load(sys.stdin).get("workers") or []))')"
echo "known workers: ${before_count}"

kubectl -n "$NS" scale statefulset/vgate-worker --replicas=3
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s
# One discovery tick rides the health-check interval; allow a couple.
sleep 15

workers_json="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}")"
echo "$workers_json" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'
after_count="$(echo "$workers_json" | python3 -c 'import json,sys; print(len(json.load(sys.stdin).get("workers") or []))')"
claim "$([[ "$after_count" -eq 3 ]] && echo 0 || echo 1)" \
    "scaling out is picked up without editing the gateway (${before_count} -> ${after_count}, want 3)"

# Identity must be the ordinal-stable pod name, not the pod address, or every
# restart adds a new label to every vgate_worker_* metric.
by_name="$(echo "$workers_json" | python3 -c '
import json, re, sys
w = json.load(sys.stdin).get("workers") or []
print(sum(1 for x in w if re.search(r"vgate-worker-\d+\.", x["endpoint"])))')"
claim "$([[ "$by_name" -eq "$after_count" ]] && echo 0 || echo 1)" \
    "workers are identified by stable pod name, not address (${by_name}/${after_count})"

echo "--- traffic reaches the newly discovered worker ---"
for i in $(seq 1 9); do ask "scale probe $(date +%s) $i" >/dev/null; done
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total{outcome="success"' || true
served="$(curl -s "http://localhost:${PORT}/metrics" \
    | { grep '^vgate_worker_requests_total{outcome="success"' || true; } | wc -l)"
claim "$([[ "$served" -eq 3 ]] && echo 0 || echo 1)" \
    "all three workers served requests (${served}/3)"

echo
echo "--- scaling back in ---"
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=2
kubectl -n "$NS" wait --for=delete pod/vgate-worker-2 --timeout=120s || true
sleep 15
shrunk="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
    | python3 -c 'import json,sys; print(len(json.load(sys.stdin).get("workers") or []))')"
claim "$([[ "$shrunk" -eq 2 ]] && echo 0 || echo 1)" \
    "a removed worker stops being tracked rather than probed forever (${shrunk}, want 2)"

echo
echo "--- scaling all the way to zero ---"
# The boundary the earlier version of this script skipped by going 1 -> 3 -> 2.
# An empty resolve is ambiguous -- a DNS blip and an empty pool read the same
# in one tick -- and the first guard against blips ignored empty answers
# unconditionally, which kept the last worker in the registry forever and went
# on probing a pod that had been deleted. Believing a repeated empty answer is
# what separates the two, and only a scale to zero exercises it.
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=0
kubectl -n "$NS" wait --for=delete pod/vgate-worker-0 --timeout=120s || true
# health_check_interval 5s x empty_resolve_threshold 3, plus slack.
sleep 30
emptied="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
    | python3 -c 'import json,sys; print(len(json.load(sys.stdin).get("workers") or []))')"
claim "$([[ "$emptied" -eq 0 ]] && echo 0 || echo 1)" \
    "scaling to zero empties the registry (known workers: ${emptied}, want 0)"

# With no workers, the gateway must shed rather than hang or pretend.
zero_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 \
    -X POST "http://localhost:${PORT}/v1/chat/completions" \
    -H "Authorization: Bearer ${API_KEY}" -H "Content-Type: application/json" \
    -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"empty pool $(date +%s)\"}],\"max_tokens\":8}" \
    || echo "000")"
claim "$([[ "$zero_code" == "503" ]] && echo 0 || echo 1)" \
    "an empty pool returns 503 rather than hanging or erroring (got ${zero_code})"

echo
echo "--- scaling back up from zero ---"
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=2
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s
sleep 15
recovered_count="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
    | python3 -c 'import json,sys; print(len(json.load(sys.stdin).get("workers") or []))')"
claim "$([[ "$recovered_count" -eq 2 ]] && echo 0 || echo 1)" \
    "a pool that was emptied repopulates (known workers: ${recovered_count}, want 2)"
recovery_answer="$(ask "post-zero probe $(date +%s)")"
echo "$recovery_answer" | grep -q '"choices"' && rc=0 || rc=1
claim "$rc" "the gateway serves again after the pool comes back"

step "13. Worker rejoins when it comes back"
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=2
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s
# success_threshold 2 at a 5s interval.
sleep 20
workers_json="$(curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}")"
echo "$workers_json" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'
echo "--- health transitions recorded by the gateway ---"
curl -s "http://localhost:${PORT}/metrics" | grep -E '^vgate_worker_(state_changes_total|healthy)' || true

echo
healthy="$(echo "$workers_json" | python3 -c '
import json, sys
w = json.load(sys.stdin).get("workers") or []
print(sum(1 for x in w if x["healthy"]))')"
claim "$([[ "$healthy" -eq 2 ]] && echo 0 || echo 1)" \
    "both workers are back in rotation (healthy: ${healthy}, want 2)"
# A returning worker rejoins as a new member rather than as a recovery, so
# there is no "recovered" transition to count here — it was scaled away, which
# removed it from DNS and from the registry, and it comes back as an arrival.
# The assertion that matters is that it is usable again, which is what the
# gateway's own served-request counters show.
# The counter's VALUE, not how many series match it. Counting series passes
# trivially here: worker-1 served requests earlier in this run, and its counter
# survives the scale-away precisely because identity is the stable pod name —
# so the series already exists before a single new request is sent. Comparing
# values is what distinguishes "is being used again" from "was used once".
served_before="$(metric_sum '^vgate_worker_requests_total\{outcome="success".*vgate-worker-1')"
for i in $(seq 1 6); do ask "rejoin probe $(date +%s) $i" >/dev/null; done
served_after="$(metric_sum '^vgate_worker_requests_total\{outcome="success".*vgate-worker-1')"
claim "$(python3 -c "print(0 if float('${served_after}') > float('${served_before}') else 1)")" \
    "the returned worker serves new requests (${served_before} -> ${served_after})"

echo "--- health transitions across the whole run ---"
# Kept as context rather than as an assertion. Cold start usually produces one
# removed/recovered pair per worker, because the gateway passes its readiness
# probe and starts probing before any worker is up — the readiness gap recorded
# in ROADMAP.md. That is a race, so its count is not something to assert on.
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_state_changes_total' || true

step "14. Gateway logs"
kubectl -n "$NS" logs deployment/vgate-gateway --tail=40

step "Result"
if [[ $FAILURES -gt 0 ]]; then
    echo "${FAILURES} assertion(s) FAILED — the deployed topology is not what this"
    echo "script claims to verify. The log above is still written to the report."
    exit 1
fi
echo "All assertions passed."
