#!/usr/bin/env bash
# Copyright 2025 the V-Gate authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Bring up the split topology on a local kind cluster and prove it works.
#
# "The manifests pass validation" and "the manifests deploy a working system"
# are different claims, and only the second one is worth anything. This script
# makes the second one reproducible: it deploys, serves a real request through
# the gateway to a worker, kills a worker, shows the gateway keeping service up
# on the survivor, and shows the worker rejoining rotation when it comes back.
#
# Everything it prints goes to an evidence file so the result can be checked in
# rather than described.
#
# Requires: docker, kind, kubectl, kustomize, python3
# Usage:    ./k8s/kind-verify.sh [--keep]
#           --keep   leave the cluster running afterwards

set -euo pipefail

CLUSTER=vgate
NS=vgate
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE="${REPO_ROOT}/docs/reports/K8S_SPLIT_VERIFICATION.md"
RAW="$(mktemp)"
PORT=18000
KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

PF_PID=""
cleanup() {
    [[ -n "$PF_PID" ]] && kill "$PF_PID" 2>/dev/null || true
    if [[ $KEEP -eq 0 ]]; then
        kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
    fi
    # Restore the real stdout before writing the report, so this output does
    # not loop back into the log being read.
    exec 1>&3 2>&3
    sleep 1  # let tee flush
    {
        echo "# Kubernetes Split Topology Verification"
        echo
        echo "Generated by \`k8s/kind-verify.sh\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
        echo
        echo "Deploys the gateway/worker split on a local kind cluster, serves a"
        echo "request end to end, removes a worker, and brings it back."
        echo
        echo '```'
        cat "$RAW"
        echo '```'
    } > "$EVIDENCE"
    rm -f "$RAW"
    echo "Evidence written to ${EVIDENCE}"
}
trap cleanup EXIT

mkdir -p "$(dirname "$EVIDENCE")"
exec 3>&1                        # keep a handle on the real stdout
exec > >(tee "$RAW") 2>&1

step() { printf '\n\n========== %s ==========\n' "$1"; }

for tool in docker kind kubectl kustomize python3; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool"; exit 1; }
done

step "0. Versions"
kind version
kubectl version --client
kustomize version

step "1. Build the CPU image"
docker build --target vgate-cpu -t vgate:cpu "$REPO_ROOT"

step "2. Create the cluster"
kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
kind create cluster --name "$CLUSTER" --config "${REPO_ROOT}/k8s/kind-cluster.yaml"

step "3. Side-load the image"
# kind nodes cannot pull from the host daemon, and the manifests set
# imagePullPolicy: IfNotPresent so this copy is the one that gets used.
kind load docker-image vgate:cpu --name "$CLUSTER"

step "4. Apply the CPU overlay"
# `kustomize build | kubectl apply` rather than `kubectl apply -k`, so the
# kustomize version is the one this repo pins in CI, not whatever kubectl
# happens to embed.
kustomize build "${REPO_ROOT}/k8s/overlays/cpu" | kubectl apply -f -

step "5. Wait for both roles to become ready"
kubectl -n "$NS" rollout status deployment/vgate-gateway --timeout=180s
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s

step "6. What actually got scheduled"
# -o wide shows the node column: the two workers should not be on the same one.
kubectl -n "$NS" get pods -o wide
echo
kubectl -n "$NS" get svc,statefulset,deployment,pvc

step "7. Worker DNS resolves per pod"
# The claim under test: each worker has its own address. If this returned one
# shared address, the gateway could not tell workers apart.
kubectl -n "$NS" run dnstest --rm -i --restart=Never --image=busybox:1.36 -- \
    sh -c 'for i in 0 1; do echo "--- vgate-worker-$i ---"; nslookup vgate-worker-$i.vgate-worker.vgate.svc.cluster.local; done' \
    || echo "(dns probe pod failed; see events above)"

step "8. Port-forward the gateway"
kubectl -n "$NS" port-forward svc/vgate "${PORT}:8000" >/dev/null 2>&1 &
PF_PID=$!
for _ in $(seq 1 30); do
    curl -sf "http://localhost:${PORT}/health" >/dev/null && break
    sleep 1
done
curl -s "http://localhost:${PORT}/health"; echo

API_KEY="$(kubectl -n "$NS" get secret vgate-secrets -o jsonpath='{.data.api-key}' | base64 -d)"

ask() {
    curl -s -X POST "http://localhost:${PORT}/v1/chat/completions" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"$1\"}],\"max_tokens\":16}"
}
workers() {
    curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
        | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'
}

step "9. A real request, gateway -> worker"
# Unique prompt each run: a cached answer would prove nothing about routing.
ask "kind verification $(date +%s)"; echo
echo "--- worker registry ---"
workers

step "10. Spread requests and confirm both workers were used"
RUN_ID="$(date +%s)"
for i in $(seq 1 8); do ask "spread probe ${RUN_ID} $i" >/dev/null; done
echo "--- per-worker request counts from the gateway's metrics ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total' || true

step "11. Remove a worker"
# Scaling down rather than deleting the pod: a deleted pod is recreated
# immediately, and a dry-run worker restarts in a few seconds while the health
# checker needs ~10s (interval 5s x failure_threshold 2) to notice it left.
# The two race, and the "removed from rotation" state can be missed entirely.
# Scaling to 1 removes the highest ordinal and keeps it gone.
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=1
kubectl -n "$NS" wait --for=delete pod/vgate-worker-1 --timeout=60s || true
echo "--- waiting for the gateway's health checker to drop it from rotation ---"
sleep 20
workers

step "12. Service continues on the survivor"
ask "survivor probe $(date +%s)"; echo

step "13. Worker rejoins when it comes back"
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=2
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s
# success_threshold 2 at a 5s interval.
sleep 20
workers
echo "--- health transitions recorded by the gateway ---"
curl -s "http://localhost:${PORT}/metrics" | grep -E '^vgate_worker_(state_changes_total|healthy)' || true

step "14. Gateway logs"
kubectl -n "$NS" logs deployment/vgate-gateway --tail=40

step "Done"
echo "Evidence written to ${EVIDENCE}"
