#!/usr/bin/env bash
# Copyright 2025 the V-Gate authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Bring up the split topology on a local kind cluster and prove it works.
#
# "The manifests pass validation" and "the manifests deploy a working system"
# are different claims, and only the second one is worth anything. This script
# makes the second one reproducible: it deploys, serves a real request through
# the gateway to a worker, kills a worker, shows the gateway keeping service up
# on the survivor, and shows the worker rejoining rotation when it comes back.
#
# Everything it prints goes to an evidence file so the result can be checked in
# rather than described.
#
# Requires: docker, kind, kubectl, kustomize, python3
# Usage:    ./k8s/kind-verify.sh [--keep]
#           --keep   leave the cluster running afterwards

set -euo pipefail

CLUSTER=vgate
NS=vgate
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE="${REPO_ROOT}/docs/reports/K8S_SPLIT_VERIFICATION.md"
RAW="$(mktemp)"
PORT=18000
KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

PF_PID=""
PROBE_PID=""
cleanup() {
    [[ -n "$PF_PID" ]] && kill "$PF_PID" 2>/dev/null || true
    [[ -n "$PROBE_PID" ]] && kill "$PROBE_PID" 2>/dev/null || true
    if [[ $KEEP -eq 0 ]]; then
        kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
    fi
    # Restore the real stdout before writing the report, so this output does
    # not loop back into the log being read.
    exec 1>&3 2>&3
    sleep 1  # let tee flush
    {
        echo "# Kubernetes Split Topology Verification"
        echo
        echo "Generated by \`k8s/kind-verify.sh\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
        echo "Regenerate with \`./k8s/kind-verify.sh\`; do not edit by hand."
        echo
        echo "Deploys the gateway/worker split on a local kind cluster, serves a"
        echo "request end to end, removes a worker while traffic is flowing, and"
        echo "brings it back."
        echo
        echo "## What to read in the log below"
        echo
        echo "- **Step 6** — the \`NODE\` column. The two workers must land on"
        echo "  different nodes, or the per-pod routing below never crosses a"
        echo "  network boundary and proves less than it appears to. The two"
        echo "  bound PVCs are the same point for storage: a single"
        echo "  \`ReadWriteOnce\` claim could not serve pods on two nodes."
        echo "- **Step 7** — the two DNS answers must be *different* addresses."
        echo "  One shared address would mean the gateway cannot tell workers"
        echo "  apart, which is what a non-headless Service would produce."
        echo "- **Step 10** — request counts should be split across both"
        echo "  workers. This is round-robin; it is not load-aware."
        echo "- **Step 11** — the status-code histogram is the real result."
        echo "  Requests keep flowing while a worker is removed, so this counts"
        echo "  what the removal cost. All \`200\` is common but not guaranteed:"
        echo "  read the outcome metrics printed underneath before concluding"
        echo "  anything from a non-200. A \`connect_error\` was never delivered"
        echo "  and gets retried on another worker; a \`request_error\` was"
        echo "  already in flight when the pod died and is deliberately not"
        echo "  retried, because the worker may already be generating and one"
        echo "  client request must not cost two generations. The second class"
        echo "  reaching the client as a 500 is the policy working, not a bug."
        echo "  Removing that window needs draining — see ROADMAP.md."
        echo "- **Step 12** — \`state_changes_total\` normally shows one extra"
        echo "  removed/recovered pair per worker beyond the scripted one. That"
        echo "  is the cold start: the gateway passes its readiness probe and"
        echo "  begins probing before any worker is up. See the readiness gap"
        echo "  noted in ROADMAP.md — a gateway with zero healthy workers is"
        echo "  still Ready as far as Kubernetes is concerned."
        echo
        echo '```'
        cat "$RAW"
        echo '```'
    } > "$EVIDENCE"
    rm -f "$RAW"
    echo "Evidence written to ${EVIDENCE}"
}
trap cleanup EXIT

mkdir -p "$(dirname "$EVIDENCE")"
exec 3>&1                        # keep a handle on the real stdout
exec > >(tee "$RAW") 2>&1

step() { printf '\n\n========== %s ==========\n' "$1"; }

for tool in docker kind kubectl kustomize python3; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool"; exit 1; }
done

step "0. Versions"
kind version
kubectl version --client
kustomize version

step "1. Build the CPU image"
docker build --target vgate-cpu -t vgate:cpu "$REPO_ROOT"

step "2. Create the cluster"
kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
kind create cluster --name "$CLUSTER" --config "${REPO_ROOT}/k8s/kind-cluster.yaml"

step "3. Side-load the image"
# kind nodes cannot pull from the host daemon, and the manifests set
# imagePullPolicy: IfNotPresent so this copy is the one that gets used.
kind load docker-image vgate:cpu --name "$CLUSTER"

step "4. Apply the CPU overlay"
# `kustomize build | kubectl apply` rather than `kubectl apply -k`, so the
# kustomize version is the one this repo pins in CI, not whatever kubectl
# happens to embed.
kustomize build "${REPO_ROOT}/k8s/overlays/cpu" | kubectl apply -f -

step "5. Wait for both roles to become ready"
kubectl -n "$NS" rollout status deployment/vgate-gateway --timeout=180s
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s

step "6. What actually got scheduled"
# -o wide shows the node column: the two workers should not be on the same one.
kubectl -n "$NS" get pods -o wide
echo
kubectl -n "$NS" get svc,statefulset,deployment,pvc

step "7. Worker DNS resolves per pod"
# The claim under test: each worker has its own address. If this returned one
# shared address, the gateway could not tell workers apart.
kubectl -n "$NS" run dnstest --rm -i --restart=Never --image=busybox:1.36 -- \
    sh -c 'for i in 0 1; do echo "--- vgate-worker-$i ---"; nslookup vgate-worker-$i.vgate-worker.vgate.svc.cluster.local; done' \
    || echo "(dns probe pod failed; see events above)"

step "8. Port-forward the gateway"
kubectl -n "$NS" port-forward svc/vgate "${PORT}:8000" >/dev/null 2>&1 &
PF_PID=$!
for _ in $(seq 1 30); do
    curl -sf "http://localhost:${PORT}/health" >/dev/null && break
    sleep 1
done
curl -s "http://localhost:${PORT}/health"; echo

API_KEY="$(kubectl -n "$NS" get secret vgate-secrets -o jsonpath='{.data.api-key}' | base64 -d)"

ask() {
    curl -s -X POST "http://localhost:${PORT}/v1/chat/completions" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"$1\"}],\"max_tokens\":16}"
}
workers() {
    curl -s "http://localhost:${PORT}/stats" -H "Authorization: Bearer ${API_KEY}" \
        | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("workers"), indent=2))'
}

step "9. A real request, gateway -> worker"
# Unique prompt each run: a cached answer would prove nothing about routing.
ask "kind verification $(date +%s)"; echo
echo "--- worker registry ---"
workers

step "10. Spread requests and confirm both workers were used"
RUN_ID="$(date +%s)"
for i in $(seq 1 8); do ask "spread probe ${RUN_ID} $i" >/dev/null; done
echo "--- per-worker request counts from the gateway's metrics ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total' || true

step "11. Remove a worker while traffic is flowing"
# The interesting window is not after the gateway has noticed the worker is
# gone — it is the ~10s before it notices (health_check_interval 5s x
# failure_threshold 2), when requests are still being routed to a pod that no
# longer exists. Serving traffic across the removal is what shows what that
# costs; asking once afterwards would only show the steady state.
#
# Scaling down rather than deleting the pod: a deleted pod is recreated
# immediately and a dry-run worker restarts in a few seconds, so the restart
# races the detection and the removed state can be missed entirely. Scaling to
# 1 removes the highest ordinal and keeps it gone.
PROBE_LOG="$(mktemp)"
STOP_FLAG="$(mktemp -u)"
(
    n=0
    while [[ ! -e "$STOP_FLAG" ]]; do
        n=$((n + 1))
        # Unique prompt per probe, so a cache hit can never stand in for a
        # successful round trip to a worker.
        code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
            -X POST "http://localhost:${PORT}/v1/chat/completions" \
            -H "Authorization: Bearer ${API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"model\":\"vgate\",\"messages\":[{\"role\":\"user\",\"content\":\"failover probe ${RUN_ID} ${n}\"}],\"max_tokens\":8}" \
            || echo "000")
        echo "$code" >> "$PROBE_LOG"
        sleep 0.25
    done
) &
PROBE_PID=$!

kubectl -n "$NS" scale statefulset/vgate-worker --replicas=1
kubectl -n "$NS" wait --for=delete pod/vgate-worker-1 --timeout=60s || true
echo "--- traffic continues while the health checker catches up ---"
sleep 20

touch "$STOP_FLAG"
wait "$PROBE_PID" 2>/dev/null || true
echo "--- HTTP status codes seen across the removal ---"
sort "$PROBE_LOG" | uniq -c
echo "    (000 = no response; 503 = every worker down; 200 = served)"
rm -f "$PROBE_LOG" "$STOP_FLAG"

echo
# Which failure class the gateway saw matters more than the count. The retry
# policy is keyed on what the worker could already have started:
#   connect_error  nothing was delivered, so another worker takes it
#   request_error  the worker may already be generating, so it is NOT retried
#                  — one client request must not cost two generations
# A non-200 above should correspond to a request_error here, not a lost retry.
echo "--- outcomes recorded per worker ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_requests_total' || true
echo "--- retries onto another worker ---"
curl -s "http://localhost:${PORT}/metrics" | grep '^vgate_worker_retries_total' || true

echo
echo "--- worker registry after detection ---"
workers

step "12. Worker rejoins when it comes back"
kubectl -n "$NS" scale statefulset/vgate-worker --replicas=2
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=180s
# success_threshold 2 at a 5s interval.
sleep 20
workers
echo "--- health transitions recorded by the gateway ---"
curl -s "http://localhost:${PORT}/metrics" | grep -E '^vgate_worker_(state_changes_total|healthy)' || true

step "13. Gateway logs"
kubectl -n "$NS" logs deployment/vgate-gateway --tail=40

step "Done"
