#!/usr/bin/env bash
# Copyright 2025 the V-Gate authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Reproduce the upgrade hazard on a kind cluster, then show the migration
# clearing it.
#
# The claim being tested is that `kubectl apply` alone is an unsafe upgrade
# path for an existing cluster, because it never deletes objects that were
# removed from the manifests. Asserting that from label arithmetic is not the
# same as watching a request land on the wrong process, so this deploys the
# pre-split manifests from git, upgrades the wrong way on purpose, and measures
# what happens to live traffic before running the migration.
#
# Phases:
#   1  deploy the pre-split manifests and confirm the monolith serves
#   2  `kubectl apply` the new manifests directly — the unsafe path
#   3  run k8s/migrate-from-monolith.sh and confirm the cluster is clean
#
# Requires: docker, kind, kubectl, kustomize, git, python3
# Usage:    ./k8s/verify-migration.sh [--from-rev <git-rev>] [--keep]

set -euo pipefail

CLUSTER=vgate-migration
NS=vgate
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE="${REPO_ROOT}/docs/reports/K8S_MIGRATION_VERIFICATION.md"
RAW="$(mktemp)"
OLD_TREE="$(mktemp -d)"
# Last commit before the split landed. Overridable so the script keeps working
# if this history is ever rewritten or the check is repeated from elsewhere.
FROM_REV="6ec4883"
KEEP=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --from-rev) FROM_REV="${2:-}"; shift 2 ;;
        --keep)     KEEP=1; shift ;;
        *)          echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

cleanup() {
    if [[ $KEEP -eq 0 ]]; then
        kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
    fi
    rm -rf "$OLD_TREE"
    exec 1>&3 2>&3
    sleep 1
    {
        echo "# Pre-Split Upgrade Hazard and Migration"
        echo
        echo "Generated by \`k8s/verify-migration.sh\` on $(date -u '+%Y-%m-%d %H:%M:%S UTC')."
        echo "Regenerate with \`./k8s/verify-migration.sh\`; do not edit by hand."
        echo
        echo "Deploys the pre-split manifests (\`${FROM_REV}\`) on a kind cluster,"
        echo "upgrades with a plain \`kubectl apply\` on purpose, measures what that"
        echo "does to live traffic, then runs the migration and re-measures."
        echo
        echo "## What to read in the log below"
        echo
        echo "- **Phase 2, endpoint list** — after the plain apply, \`Service/vgate\`"
        echo "  should list *both* the old monolith pod and the new gateway pod."
        echo "  The old pods carry \`app.kubernetes.io/component=gateway\`, which is"
        echo "  exactly what the new Service selects on, so nothing removes them."
        echo "- **Phase 2, response tally** — traffic sent through the Service from"
        echo "  inside the cluster, so kube-proxy load balances it. Responses"
        echo "  split between the two processes. The old monolith still validates"
        echo "  the API key from the ConfigMap it mounted at start, not the one"
        echo "  the new Secret supplies, so its share comes back \`401\`; a"
        echo "  \`200\` whose /stats has no \`workers\` key is the monolith"
        echo "  answering an inference path that does no worker routing at all."
        echo "- **Phase 3** — the same tally after migrating. Every response"
        echo "  should come from the new gateway, and no pre-split object should"
        echo "  remain."
        echo
        echo '```'
        cat "$RAW"
        echo '```'
    } > "$EVIDENCE"
    rm -f "$RAW"
    echo "Evidence written to ${EVIDENCE}"
}
trap cleanup EXIT

mkdir -p "$(dirname "$EVIDENCE")"
exec 3>&1
exec > >(tee "$RAW") 2>&1

step() { printf '\n\n========== %s ==========\n' "$1"; }

for tool in docker kind kubectl kustomize git python3; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool"; exit 1; }
done

step "0. Extract the pre-split manifests from ${FROM_REV}"
git -C "$REPO_ROOT" archive "$FROM_REV" k8s | tar -x -C "$OLD_TREE"
kustomize build "${OLD_TREE}/k8s/overlays/cpu" 2>/dev/null | python3 -c '
import sys, yaml
print("pre-split overlay renders:")
for d in yaml.safe_load_all(sys.stdin):
    if d:
        print("  %-26s %s" % (d["kind"], d["metadata"]["name"]))
'

step "1. Cluster and image"
kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
kind create cluster --name "$CLUSTER" --config "${REPO_ROOT}/k8s/kind-cluster.yaml"
docker build --target vgate-cpu -t vgate:cpu "$REPO_ROOT" >/dev/null
kind load docker-image vgate:cpu --name "$CLUSTER"

step "2. Deploy the pre-split manifests"
kustomize build "${OLD_TREE}/k8s/overlays/cpu" 2>/dev/null | kubectl apply -f -
kubectl -n "$NS" rollout status deployment/vgate --timeout=180s
kubectl -n "$NS" get pods -o wide

# The pre-split ConfigMap carried its own API key inline; the new manifests
# take it from the Secret instead. Both are needed below, because the old pods
# keep validating against whatever they mounted at startup.
OLD_KEY="PLACEHOLDER_REPLACE_WITH_REAL_KEY"
NEW_KEY="$(kubectl -n "$NS" get secret vgate-secrets -o jsonpath='{.data.api-key}' | base64 -d)"
echo
echo "old pods validate against: ${OLD_KEY}"
echo "new manifests supply:      ${NEW_KEY}"

# Send traffic through the Service's cluster IP from inside the cluster so
# kube-proxy distributes it. A host-side port-forward pins one pod and would
# hide the split entirely.
tally() {
    local key=$1 count=$2
    # One request per iteration, with the status code appended to the body.
    # Fetching them with two separate curls would let kube-proxy send each to a
    # different pod, and the classification would then describe neither.
    #
    # The leading sleep is not padding: `kubectl run -i` loses whatever the
    # container prints before its attach finishes, which silently dropped one
    # or two samples per run and left the totals short of `count` with no
    # explanation. Waiting before the first line makes the tally add up.
    kubectl -n "$NS" run tally-$RANDOM --rm -i --restart=Never --quiet \
        --image=curlimages/curl:8.10.1 --command -- \
        sh -c "sleep 1
               for i in \$(seq 1 ${count}); do
                 out=\$(curl -s -m 5 -w '\n%{http_code}' -H 'Authorization: Bearer ${key}' http://vgate:8000/stats)
                 code=\$(echo \"\$out\" | tail -n 1)
                 body=\$(echo \"\$out\" | sed '\$d')
                 if [ \"\$code\" != 200 ]; then echo \"HTTP-\$code\";
                 elif echo \"\$body\" | grep -q '\"workers\"'; then echo 'new-gateway';
                 else echo 'OLD-MONOLITH'; fi
               done" 2>/dev/null | sort | uniq -c
}

step "3. Baseline: only the monolith exists"
echo "--- 20 requests with the old key ---"
tally "$OLD_KEY" 20

step "4. THE UNSAFE PATH: plain kubectl apply, exactly as a naive upgrade would"
kustomize build "${REPO_ROOT}/k8s/overlays/cpu" | kubectl apply -f -
kubectl -n "$NS" rollout status deployment/vgate-gateway --timeout=180s
kubectl -n "$NS" rollout status statefulset/vgate-worker --timeout=300s

echo
echo "--- workloads now present ---"
kubectl -n "$NS" get deployment,statefulset,hpa,pvc

echo
echo "--- Service/vgate endpoints: old monolith and new gateway together? ---"
kubectl -n "$NS" get endpointslice -l kubernetes.io/service-name=vgate \
    -o jsonpath='{range .items[*]}{range .endpoints[*]}  {.addresses[0]}  {.targetRef.name}{"\n"}{end}{end}'

echo
echo "--- 40 requests with the NEW key, through the Service ---"
tally "$NEW_KEY" 40
echo "    HTTP-401     = answered by the old monolith, which never saw the new key"
echo "    OLD-MONOLITH = answered by the old monolith (200, but no worker routing)"
echo "    new-gateway  = answered by the split gateway"

step "5. Detect the orphans"
"${REPO_ROOT}/k8s/migrate-from-monolith.sh" --check || true

step "6. Migrate"
"${REPO_ROOT}/k8s/migrate-from-monolith.sh" --overlay cpu --delete-pvc

step "7. Re-measure: every response should come from the new gateway"
echo "--- 40 requests with the NEW key ---"
tally "$NEW_KEY" 40

step "8. Confirm nothing pre-split remains"
"${REPO_ROOT}/k8s/migrate-from-monolith.sh" --check
kubectl -n "$NS" get deployment,statefulset,hpa,pvc

step "Done"
